on:
  schedule:
    - cron: "0 0 * * *"
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: cd src && npm ci && npm start
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          push: origin HEAD:main --force
